### ISSUE TITLE
compil and render only render bed

### ISSUE THREAD

**Issue by pomalin** [whosawhatsis/RepRap-Wallace#15]
when I hit F6, in openscad, it only render the bed I have to hit F5 to have the all machine, but I was wanted to export the machine in stl, is there a way to do it ? or did I miss something?

**Comment by whosawhatsis** [comment]
The platform is included as a 2D shape for cutting with a laser cutter or similar, but CGAL can't render a scene with both 2D and 3D shapes in it. To make it work, just extrude the platform into a 3d shape so that everything will be 3d.

When you do this, you won't get the various belts, rods, etc. that appear transparent in the OpenCSG render. To include those, you'll have to go through the code and remove each instance of the % modifier.

**Comment by pomalin** [comment]
Ok I will do that, thank you.

Imaurf emmanuel-paul
http://imaurf.fr
